#!/usr/bin/env node
/**
 * Copies Quire build output to the site repo and writes _data/quire-assets.yml
 * so the site layout can embed the app (no iframe). Run after: npm run build
 *
 * Usage: node scripts/sync-to-site.js [path-to-site-repo]
 *        or set SITE_DIR env var
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const quireRoot = path.resolve(__dirname, '..');
const distDir = path.join(quireRoot, 'dist');
const siteDir = process.env.SITE_DIR || process.argv[2];
const targetDir = siteDir ? path.resolve(siteDir, 'projects', 'quire') : null;

if (!siteDir || !targetDir) {
  console.error('Usage: node scripts/sync-to-site.js <path-to-site-repo>');
  console.error('   or: SITE_DIR=/path/to/site node scripts/sync-to-site.js');
  process.exit(1);
}

if (!fs.existsSync(distDir)) {
  console.error('Run "npm run build" first.');
  process.exit(1);
}

const indexHtml = fs.readFileSync(path.join(distDir, 'index.html'), 'utf8');

// Extract asset paths (already with base /projects/quire/)
const cssMatch = indexHtml.match(/<link[^>]+rel="stylesheet"[^>]+href="([^"]+)"/);
const moduleScriptMatch = indexHtml.match(/<script[^>]+type="module"[^>]+src="([^"]+)"/);
const registerSwMatch = indexHtml.match(/<script[^>]+id="vite-plugin-pwa:register-sw"[^>]+src="([^"]+)"/);

const assets = {
  css: cssMatch ? cssMatch[1] : null,
  js: moduleScriptMatch ? moduleScriptMatch[1] : null,
  register_sw: registerSwMatch ? registerSwMatch[1] : null,
};

// Copy dist/assets/* to site/projects/quire/assets/
const assetsSrc = path.join(distDir, 'assets');
const assetsDest = path.join(targetDir, 'assets');
if (fs.existsSync(assetsSrc)) {
  if (!fs.existsSync(assetsDest)) fs.mkdirSync(assetsDest, { recursive: true });
  for (const name of fs.readdirSync(assetsSrc)) {
    fs.copyFileSync(path.join(assetsSrc, name), path.join(assetsDest, name));
  }
  console.log('Copied assets/');
}

// Copy registerSW.js, manifest, sw, workbox
for (const name of ['registerSW.js', 'manifest.webmanifest', 'sw.js']) {
  const src = path.join(distDir, name);
  if (fs.existsSync(src)) {
    fs.copyFileSync(src, path.join(targetDir, name));
    console.log('Copied', name);
  }
}
const workboxFiles = fs.readdirSync(distDir).filter((n) => n.startsWith('workbox-'));
workboxFiles.forEach((name) => {
  fs.copyFileSync(path.join(distDir, name), path.join(targetDir, name));
  console.log('Copied', name);
});

// Write _data/quire-assets.yml
const dataDir = path.join(siteDir, '_data');
if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir, { recursive: true });
const yaml = `# Generated by quire/scripts/sync-to-site.js — do not edit by hand
css: ${assets.css || ''}
js: ${assets.js || ''}
register_sw: ${assets.register_sw || ''}
`;
fs.writeFileSync(path.join(dataDir, 'quire-assets.yml'), yaml);
console.log('Wrote _data/quire-assets.yml');
console.log('Done. Commit site repo and push to deploy.');